name: units_helper
description: A library provides unit helpers and extensions to simplifying the code.
version: 0.0.1
homepage: https://github.com/gokuzhan/units_helper.git
maintainer: Gokul Kannan (@gokuzhan)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
